using System.Collections.Generic;
using System.Collections.Immutable;

namespace ToyHack
{
    public enum MedalCategory
    {
        Normal,
        Z,
        Common
    }

    public struct YokaiMedal
    {
        public string Name { get; }
        public ushort Pattern { get; }
        public MedalCategory Category { get; }

        public YokaiMedal(string Name, ushort Pattern, MedalCategory Category)
        {
            this.Name = Name;
            this.Pattern = Pattern;
            this.Category = Category;
        }

        // $ grep 'const char' yokai-medal.h | sed -e 's/^.\+\(".\+"\), \(0x[0-9a-f]\+\).\+$/new YokaiMedal(\1, \2, MedalCategory.Normal),/g'
        public static readonly ImmutableHashSet<YokaiMedal> MEDALS = ImmutableHashSet.Create(
            new YokaiMedal("ぶようじん坊", 0x94ea, MedalCategory.Normal),
            new YokaiMedal("がらあきん坊", 0x94fa, MedalCategory.Normal),
            new YokaiMedal("さきがけの助", 0x961a, MedalCategory.Normal),
            new YokaiMedal("ダラケ刀", 0x962a, MedalCategory.Normal),
            new YokaiMedal("ザンバラ刀", 0x963a, MedalCategory.Normal),
            new YokaiMedal("ダララだんびら", 0x964a, MedalCategory.Normal),
            new YokaiMedal("ちからモチ", 0x967a, MedalCategory.Normal),
            new YokaiMedal("やきモチ", 0x968a, MedalCategory.Normal),
            new YokaiMedal("カブトさん", 0x96ba, MedalCategory.Normal),
            new YokaiMedal("ゲンマ将軍", 0x96ca, MedalCategory.Normal),
            new YokaiMedal("黄泉ゲンスイ", 0x96da, MedalCategory.Normal),
            new YokaiMedal("メラメライオン", 0x96ea, MedalCategory.Normal),
            new YokaiMedal("グラグライオン", 0x96fa, MedalCategory.Normal),
            new YokaiMedal("轟獅子", 0x971a, MedalCategory.Normal),
            new YokaiMedal("しょうブシ", 0x972a, MedalCategory.Normal),
            new YokaiMedal("まさむね", 0x973a, MedalCategory.Normal),
            new YokaiMedal("むらまさ", 0x974a, MedalCategory.Normal),
            new YokaiMedal("くさなぎ", 0x976a, MedalCategory.Normal),
            new YokaiMedal("ベンケイ", 0x978a, MedalCategory.Normal),
            new YokaiMedal("からくりベンケイ", 0x97ba, MedalCategory.Normal),
            new YokaiMedal("やまと", 0x97ca, MedalCategory.Normal),
            new YokaiMedal("かぶき猿", 0x97da, MedalCategory.Normal),
            new YokaiMedal("クワノ武士", 0x97ea, MedalCategory.Normal),
            new YokaiMedal("クワガ大将", 0x97fa, MedalCategory.Normal),
            new YokaiMedal("オオクワノ神", 0x981a, MedalCategory.Normal),
            new YokaiMedal("くしゃ武者", 0x982a, MedalCategory.Normal),
            new YokaiMedal("なまはげ", 0x983a, MedalCategory.Normal),
            new YokaiMedal("ズルズルづる", 0x984a, MedalCategory.Normal),
            new YokaiMedal("かぜカモ", 0x986a, MedalCategory.Normal),
            new YokaiMedal("わすれん帽", 0x987a, MedalCategory.Normal),
            new YokaiMedal("ばか頭巾", 0x98ba, MedalCategory.Normal),
            new YokaiMedal("つづかな僧", 0x98ca, MedalCategory.Normal),
            new YokaiMedal("やめたい師", 0x98da, MedalCategory.Normal),
            new YokaiMedal("もうせん和尚", 0x98ea, MedalCategory.Normal),
            new YokaiMedal("わらえ姉", 0x98fa, MedalCategory.Normal),
            new YokaiMedal("青くちびる", 0x9b1a, MedalCategory.Normal),
            new YokaiMedal("バクロ婆", 0x9b2a, MedalCategory.Normal),
            new YokaiMedal("ババァーン", 0x9b3a, MedalCategory.Normal),
            new YokaiMedal("ドクロ婆", 0x9b4a, MedalCategory.Normal),
            new YokaiMedal("モテモ天", 0x9b6a, MedalCategory.Normal),
            new YokaiMedal("モテマクール", 0x9b7a, MedalCategory.Normal),
            new YokaiMedal("モテヌス", 0x9b8a, MedalCategory.Normal),
            new YokaiMedal("でんぱく小僧", 0x9bca, MedalCategory.Normal),
            new YokaiMedal("でんじん", 0x9bda, MedalCategory.Normal),
            new YokaiMedal("はつでんしん", 0x9bea, MedalCategory.Normal),
            new YokaiMedal("うんがい鏡", 0x9bfa, MedalCategory.Normal),
            new YokaiMedal("ヤミ鏡", 0x9c1a, MedalCategory.Normal),
            new YokaiMedal("まぼ老師", 0x9c2a, MedalCategory.Normal),
            new YokaiMedal("かげ老師", 0x9c3a, MedalCategory.Normal),
            new YokaiMedal("ほう老師", 0x9c4a, MedalCategory.Normal),
            new YokaiMedal("さとりちゃん", 0x9c6a, MedalCategory.Normal),
            new YokaiMedal("よつめ", 0x9c7a, MedalCategory.Normal),
            new YokaiMedal("天狗", 0x9c8a, MedalCategory.Normal),
            new YokaiMedal("ほむら天狗", 0x9cba, MedalCategory.Normal),
            new YokaiMedal("キュウビ", 0x9cda, MedalCategory.Normal),
            new YokaiMedal("犬神", 0x9cea, MedalCategory.Normal),
            new YokaiMedal("ダルダルマ", 0x9cfa, MedalCategory.Normal),
            new YokaiMedal("ダルマッチョ", 0x9d1a, MedalCategory.Normal),
            new YokaiMedal("ゴリダルマ", 0x9d2a, MedalCategory.Normal),
            new YokaiMedal("ムリカベ", 0x9d3a, MedalCategory.Normal),
            new YokaiMedal("むりだ城", 0x9d4a, MedalCategory.Normal),
            new YokaiMedal("シロカベ", 0x9d6a, MedalCategory.Normal),
            new YokaiMedal("ヨロイさん", 0x9d7a, MedalCategory.Normal),
            new YokaiMedal("モレゾウ", 0x9d8a, MedalCategory.Normal),
            new YokaiMedal("プルファント", 0x9dba, MedalCategory.Normal),
            new YokaiMedal("トオセンボン", 0x9dca, MedalCategory.Normal),
            new YokaiMedal("くろがねセンボン", 0x9dea, MedalCategory.Normal),
            new YokaiMedal("ふじのやま", 0x9dfa, MedalCategory.Normal),
            new YokaiMedal("さくらのじま", 0x9e1a, MedalCategory.Normal),
            new YokaiMedal("グレるりん", 0x9e2a, MedalCategory.Normal),
            new YokaiMedal("ゴクドー", 0x9e3a, MedalCategory.Normal),
            new YokaiMedal("あに鬼", 0x9e4a, MedalCategory.Normal),
            new YokaiMedal("武者カブト", 0x9e6a, MedalCategory.Normal),
            new YokaiMedal("カブト無双", 0x9e7a, MedalCategory.Normal),
            new YokaiMedal("オオツノノ神", 0x9e8a, MedalCategory.Normal),
            new YokaiMedal("ドウカク", 0x9eba, MedalCategory.Normal),
            new YokaiMedal("ギンカク", 0x9eca, MedalCategory.Normal),
            new YokaiMedal("キンカク", 0x9eda, MedalCategory.Normal),
            new YokaiMedal("プラチナカク", 0x9efa, MedalCategory.Normal),
            new YokaiMedal("ロボニャン", 0x9f1a, MedalCategory.Normal),
            new YokaiMedal("ゴルニャン", 0x9f2a, MedalCategory.Normal),
            new YokaiMedal("だいだらぼっち", 0x9f3a, MedalCategory.Normal),
            new YokaiMedal("うみぼうず", 0x9f4a, MedalCategory.Normal),
            new YokaiMedal("しゃれこ婦人", 0x9f6a, MedalCategory.Normal),
            new YokaiMedal("カラカラさん", 0x9f7a, MedalCategory.Normal),
            new YokaiMedal("ほね美人", 0x9f8a, MedalCategory.Normal),
            new YokaiMedal("セミまる", 0x9fba, MedalCategory.Normal),
            new YokaiMedal("カゲまる", 0x9fca, MedalCategory.Normal),
            new YokaiMedal("ヒグラシまる", 0x9fda, MedalCategory.Normal),
            new YokaiMedal("さむガリ", 0x9fea, MedalCategory.Normal),
            new YokaiMedal("ガリ王子", 0xb4ea, MedalCategory.Normal),
            new YokaiMedal("あつガルル", 0xb4fa, MedalCategory.Normal),
            new YokaiMedal("ジバニャン", 0xb61a, MedalCategory.Normal),
            new YokaiMedal("とげニャン", 0xb62a, MedalCategory.Normal),
            new YokaiMedal("ワルニャン", 0xb63a, MedalCategory.Normal),
            new YokaiMedal("ノガッパ", 0xb64a, MedalCategory.Normal),
            new YokaiMedal("たびガッパ", 0xb67a, MedalCategory.Normal),
            new YokaiMedal("なみガッパ", 0xb68a, MedalCategory.Normal),
            new YokaiMedal("コマさん", 0xb69a, MedalCategory.Normal),
            new YokaiMedal("ししコマ", 0xb6ca, MedalCategory.Normal),
            new YokaiMedal("コマじろう", 0xb6da, MedalCategory.Normal),
            new YokaiMedal("とらじろう", 0xb6ea, MedalCategory.Normal),
            new YokaiMedal("バク", 0xb6fa, MedalCategory.Normal),
            new YokaiMedal("ハク", 0xb71a, MedalCategory.Normal),
            new YokaiMedal("キュン太郎", 0xb72a, MedalCategory.Normal),
            new YokaiMedal("ズキュキュン太", 0xb73a, MedalCategory.Normal),
            new YokaiMedal("裏キュン太", 0xb74a, MedalCategory.Normal),
            new YokaiMedal("ゆきおんな", 0xb76a, MedalCategory.Normal),
            new YokaiMedal("ふぶき姫", 0xb78a, MedalCategory.Normal),
            new YokaiMedal("百鬼姫", 0xb79a, MedalCategory.Normal),
            new YokaiMedal("ワカメくん", 0xb7ca, MedalCategory.Normal),
            new YokaiMedal("コンブさん", 0xb7da, MedalCategory.Normal),
            new YokaiMedal("メカブちゃん", 0xb7ea, MedalCategory.Normal),
            new YokaiMedal("うらやましろう", 0xb7fa, MedalCategory.Normal),
            new YokaiMedal("つまみぐいのすけ", 0xb81a, MedalCategory.Normal),
            new YokaiMedal("ひも爺", 0xb82a, MedalCategory.Normal),
            new YokaiMedal("くいい爺", 0xb83a, MedalCategory.Normal),
            new YokaiMedal("こめ爺", 0xb84a, MedalCategory.Normal),
            new YokaiMedal("びんボーイ", 0xb86a, MedalCategory.Normal),
            new YokaiMedal("らくてん童", 0xb87a, MedalCategory.Normal),
            new YokaiMedal("ぜっこう蝶", 0xb89a, MedalCategory.Normal),
            new YokaiMedal("ぜっこう蝶", 0xb8ca, MedalCategory.Normal),
            new YokaiMedal("サイコウ蝶", 0xb8da, MedalCategory.Normal),
            new YokaiMedal("アゲアゲハ", 0xb8ea, MedalCategory.Normal),
            new YokaiMedal("ホノボーノ", 0xb8fa, MedalCategory.Normal),
            new YokaiMedal("ヒョウヘンヌ", 0xb91a, MedalCategory.Normal),
            new YokaiMedal("ヒョウヘンナ", 0xb92a, MedalCategory.Normal),
            new YokaiMedal("サンタク老師", 0xb93a, MedalCategory.Normal),
            new YokaiMedal("ふくろじじい", 0xb94a, MedalCategory.Normal),
            new YokaiMedal("さいの目入道", 0xb96a, MedalCategory.Normal),
            new YokaiMedal("ゾロ目大明神", 0xb97a, MedalCategory.Normal),
            new YokaiMedal("雷オトン", 0xb98a, MedalCategory.Normal),
            new YokaiMedal("絶オジイ", 0xb9ca, MedalCategory.Normal),
            new YokaiMedal("聖オカン", 0xb9da, MedalCategory.Normal),
            new YokaiMedal("心オバア", 0xb9ea, MedalCategory.Normal),
            new YokaiMedal("みちび鬼", 0xb9fa, MedalCategory.Normal),
            new YokaiMedal("えこひい鬼", 0xbc1a, MedalCategory.Normal),
            new YokaiMedal("かたのり小僧", 0xbc2a, MedalCategory.Normal),
            new YokaiMedal("かたのり親方", 0xbc3a, MedalCategory.Normal),
            new YokaiMedal("ぎっくり男", 0xbc4a, MedalCategory.Normal),
            new YokaiMedal("ネガティブーン", 0xbc6a, MedalCategory.Normal),
            new YokaiMedal("ジャネガブーン", 0xbc7a, MedalCategory.Normal),
            new YokaiMedal("かゆかゆ", 0xbc8a, MedalCategory.Normal),
            new YokaiMedal("ジミー", 0xbc9a, MedalCategory.Normal),
            new YokaiMedal("カゲロー", 0xbcda, MedalCategory.Normal),
            new YokaiMedal("カイム", 0xbcea, MedalCategory.Normal),
            new YokaiMedal("ヒキコウモリ", 0xbcfa, MedalCategory.Normal),
            new YokaiMedal("トジコウモリ", 0xbd1a, MedalCategory.Normal),
            new YokaiMedal("ヤドコウモリ", 0xbd2a, MedalCategory.Normal),
            new YokaiMedal("ぎしんあん鬼", 0xbd3a, MedalCategory.Normal),
            new YokaiMedal("ガ鬼", 0xbd4a, MedalCategory.Normal),
            new YokaiMedal("あまのじゃく", 0xbd6a, MedalCategory.Normal),
            new YokaiMedal("ネクラマテング", 0xbd7a, MedalCategory.Normal),
            new YokaiMedal("ヨミテング", 0xbd8a, MedalCategory.Normal),
            new YokaiMedal("魔ガサス", 0xbd9a, MedalCategory.Normal),
            new YokaiMedal("ウ魔", 0xbdca, MedalCategory.Normal),
            new YokaiMedal("デビビル", 0xbdea, MedalCategory.Normal),
            new YokaiMedal("デビビラン", 0xbdfa, MedalCategory.Normal),
            new YokaiMedal("虫歯伯爵", 0xbe1a, MedalCategory.Normal),
            new YokaiMedal("ドケチング", 0xbe2a, MedalCategory.Normal),
            new YokaiMedal("ヤミまろ", 0xbe3a, MedalCategory.Normal),
            new YokaiMedal("イガイガグリ", 0xbe4a, MedalCategory.Normal),
            new YokaiMedal("チクチクウニ", 0xbe6a, MedalCategory.Normal),
            new YokaiMedal("ヨコドリ", 0xbe7a, MedalCategory.Normal),
            new YokaiMedal("はらおドリ", 0xbe8a, MedalCategory.Normal),
            new YokaiMedal("トホホギス", 0xbe9a, MedalCategory.Normal),
            new YokaiMedal("ブカッコウ", 0xbeca, MedalCategory.Normal),
            new YokaiMedal("死神鳥", 0xbeda, MedalCategory.Normal),
            new YokaiMedal("じんめん犬", 0xbefa, MedalCategory.Normal),
            new YokaiMedal("かおベロス", 0xbf1a, MedalCategory.Normal),
            new YokaiMedal("三途の犬", 0xbf2a, MedalCategory.Normal),
            new YokaiMedal("じめりんぼう", 0xbf3a, MedalCategory.Normal),
            new YokaiMedal("雨ふらし", 0xbf4a, MedalCategory.Normal),
            new YokaiMedal("こおりんぼう", 0xbf6a, MedalCategory.Normal),
            new YokaiMedal("化けあられ", 0xbf7a, MedalCategory.Normal),
            new YokaiMedal("たらりん", 0xbf8a, MedalCategory.Normal),
            new YokaiMedal("口だけおんな", 0xbf9a, MedalCategory.Normal),
            new YokaiMedal("おつぼね様", 0xbfca, MedalCategory.Normal),
            new YokaiMedal("ドンヨリーヌ", 0xbfda, MedalCategory.Normal),
            new YokaiMedal("おならず者", 0xbfea, MedalCategory.Normal),
            new YokaiMedal("へこ鬼神", 0xd4ea, MedalCategory.Normal),
            new YokaiMedal("おすべり様", 0xd4fa, MedalCategory.Normal),
            new YokaiMedal("おしっしょう", 0xd61a, MedalCategory.Normal),
            new YokaiMedal("しわくちゃん", 0xd62a, MedalCategory.Normal),
            new YokaiMedal("おいらん", 0xd63a, MedalCategory.Normal),
            new YokaiMedal("ふじみ御前", 0xd64a, MedalCategory.Normal),
            new YokaiMedal("ふぅみん", 0xd67a, MedalCategory.Normal),
            new YokaiMedal("おねむの精", 0xd68a, MedalCategory.Normal),
            new YokaiMedal("ツチノコ", 0xd69a, MedalCategory.Normal),
            new YokaiMedal("フクリュウ", 0xd6ba, MedalCategory.Normal),
            new YokaiMedal("ツチノコパンダ", 0xd6ca, MedalCategory.Normal),
            new YokaiMedal("笑ウツボ", 0xd6ea, MedalCategory.Normal),
            new YokaiMedal("歌ウナギ", 0xd6fa, MedalCategory.Normal),
            new YokaiMedal("大蛇のツボ", 0xd71a, MedalCategory.Normal),
            new YokaiMedal("キライギョ", 0xd72a, MedalCategory.Normal),
            new YokaiMedal("ゾウオ", 0xd73a, MedalCategory.Normal),
            new YokaiMedal("キャクジョウオ", 0xd74a, MedalCategory.Normal),
            new YokaiMedal("りゅーくん", 0xd76a, MedalCategory.Normal),
            new YokaiMedal("龍神", 0xd78a, MedalCategory.Normal),
            new YokaiMedal("青龍", 0xd79a, MedalCategory.Normal),
            new YokaiMedal("ボー坊", 0xd7ba, MedalCategory.Normal),
            new YokaiMedal("しどろもどろ", 0xd7ca, MedalCategory.Normal),
            new YokaiMedal("ミチクサメ", 0xd7ea, MedalCategory.Normal),
            new YokaiMedal("トーシロザメ", 0xd7fa, MedalCategory.Normal),
            new YokaiMedal("ムダヅカイ", 0xd81a, MedalCategory.Normal),
            new YokaiMedal("はらわシェル", 0xd82a, MedalCategory.Normal),
            new YokaiMedal("ナガバナ", 0xd83a, MedalCategory.Normal),
            new YokaiMedal("ナガバナナ", 0xd84a, MedalCategory.Normal),
            new YokaiMedal("しきるん蛇", 0xd86a, MedalCategory.Normal),
            new YokaiMedal("すねスネーク", 0xd87a, MedalCategory.Normal),
            new YokaiMedal("まむし行司", 0xd89a, MedalCategory.Normal),
            new YokaiMedal("オロチ", 0xd8ba, MedalCategory.Normal),
            new YokaiMedal("影オロチ", 0xd8ca, MedalCategory.Normal),
            new YokaiMedal("ブシニャン", 0xd8ea, MedalCategory.Normal),
            new YokaiMedal("しゅらコマ", 0xd8fa, MedalCategory.Normal),
            new YokaiMedal("イケメン犬", 0xd91a, MedalCategory.Normal),
            new YokaiMedal("花咲爺", 0xd92a, MedalCategory.Normal),
            new YokaiMedal("山吹鬼", 0xd93a, MedalCategory.Normal),
            new YokaiMedal("サファイニャン", 0xd94a, MedalCategory.Normal),
            new YokaiMedal("エメラルニャン", 0xd96a, MedalCategory.Normal),
            new YokaiMedal("ルビニャン", 0xd97a, MedalCategory.Normal),
            new YokaiMedal("トパニャン", 0xd98a, MedalCategory.Normal),
            new YokaiMedal("ダイヤニャン", 0xd9ba, MedalCategory.Normal),

            new YokaiMedal("スペシャルいいことおっしゃる", 0xd9ca, MedalCategory.Common),
            new YokaiMedal("アンビリーバボーなんでそうなの", 0xd9ea, MedalCategory.Common),
            new YokaiMedal("イッツアメージング", 0xd9fa, MedalCategory.Common),
            new YokaiMedal("ファンタスティックなんだそれ", 0xdb1a, MedalCategory.Common),
            new YokaiMedal("コングラッチュレイションこんぐらいのもんでしょ", 0xdb2a, MedalCategory.Common),
            new YokaiMedal("スゴイネやるねやるもんだね", 0xdb3a, MedalCategory.Common),
            new YokaiMedal("コロコロコロコロコーロコロ", 0xdb4a, MedalCategory.Common),
            new YokaiMedal("ゲラゲラポー", 0xdb6a, MedalCategory.Common),
            new YokaiMedal("ゲラゲラポー", 0xdb7a, MedalCategory.Common),

            new YokaiMedal("ロボりゅうくん", 0x153a, MedalCategory.Z),
            new YokaiMedal("スイカニャン", 0x154a, MedalCategory.Z),
            new YokaiMedal("メロンニャン", 0x156a, MedalCategory.Z),
            new YokaiMedal("しゅらコマ", 0x157a, MedalCategory.Z),
            new YokaiMedal("キウイニャン", 0x158a, MedalCategory.Z),
            new YokaiMedal("山吹鬼", 0x159a, MedalCategory.Z),
            new YokaiMedal("イケメン犬", 0x15ba, MedalCategory.Z),
            new YokaiMedal("花さか爺", 0x15ca, MedalCategory.Z),
            new YokaiMedal("ブシニャン", 0x15da, MedalCategory.Z),
            new YokaiMedal("りゅうくん", 0x15ea, MedalCategory.Z),
            new YokaiMedal("イチゴニャン", 0x15fa, MedalCategory.Z),
            new YokaiMedal("ジコチュウ", 0x357a, MedalCategory.Z),
            new YokaiMedal("スティーブジョーズ", 0x359a, MedalCategory.Z),
            new YokaiMedal("イザナミ", 0x35ba, MedalCategory.Z),
            new YokaiMedal("アペリカン", 0x35ca, MedalCategory.Z),
            new YokaiMedal("女郎蜘蛛", 0x35da, MedalCategory.Z),
            new YokaiMedal("一角", 0x35ea, MedalCategory.Z),
            new YokaiMedal("Mr.ムービーン", 0x35fa, MedalCategory.Z),
            new YokaiMedal("コマさん 前略お母ちゃん", 0x651a, MedalCategory.Z),
            new YokaiMedal("コマじろう にーさんスゲーずら", 0x653a, MedalCategory.Z),
            new YokaiMedal("天狗", 0x658a, MedalCategory.Z),
            new YokaiMedal("コマさん 今日からともだちずら", 0x659a, MedalCategory.Z),
            new YokaiMedal("ジバニャン ニャーケービー", 0x65ba, MedalCategory.Z),
            new YokaiMedal("ダークニャン 地獄におちニャン", 0x65ca, MedalCategory.Z),
            new YokaiMedal("ジバニャン 百烈肉球", 0x65da, MedalCategory.Z),
            new YokaiMedal("ヒキコウモリ", 0x65ea, MedalCategory.Z),
            new YokaiMedal("トゲニャン", 0x65fa, MedalCategory.Z),
            new YokaiMedal("ブチニャン　ウイッス", 0x751a, MedalCategory.Z),
            new YokaiMedal("ブリー隊長 イチニッサンホー", 0x752a, MedalCategory.Z),
            new YokaiMedal("なんかい", 0x753a, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0x754a, MedalCategory.Z),
            new YokaiMedal("はかい", 0x756a, MedalCategory.Z),
            new YokaiMedal("あかまる", 0x758a, MedalCategory.Z),
            new YokaiMedal("ゴーカイ", 0x759a, MedalCategory.Z),
            new YokaiMedal("泥太坊怪", 0x75ba, MedalCategory.Z),
            new YokaiMedal("不快", 0x75ca, MedalCategory.Z),
            new YokaiMedal("あかなめ怪", 0x75da, MedalCategory.Z),
            new YokaiMedal("ノガッパ クワッ", 0x75ea, MedalCategory.Z),
            new YokaiMedal("やっかい", 0x75fa, MedalCategory.Z),
            new YokaiMedal("ロボガッパ", 0x85ba, MedalCategory.Z),
            new YokaiMedal("ロボメン犬", 0x85da, MedalCategory.Z),
            new YokaiMedal("ロボノコ", 0x85ea, MedalCategory.Z),
            new YokaiMedal("獅子まる", 0xc12a, MedalCategory.Z),
            new YokaiMedal("かたづ家来", 0xc13a, MedalCategory.Z),
            new YokaiMedal("おこ武者", 0xc14a, MedalCategory.Z),
            new YokaiMedal("おにぎり侍", 0xc16a, MedalCategory.Z),
            new YokaiMedal("あかなめ", 0xc17a, MedalCategory.Z),
            new YokaiMedal("泥田坊", 0xc18a, MedalCategory.Z),
            new YokaiMedal("ブリー隊長", 0xc19a, MedalCategory.Z),
            new YokaiMedal("アライ魔将", 0xc1ba, MedalCategory.Z),
            new YokaiMedal("フユニャン", 0xc1da, MedalCategory.Z),
            new YokaiMedal("万尾獅子", 0xc1ea, MedalCategory.Z),
            new YokaiMedal("焼きおに斬り", 0xc1fa, MedalCategory.Z),
            new YokaiMedal("鬼食い", 0xc21a, MedalCategory.Z),
            new YokaiMedal("さかさ傘", 0xc23a, MedalCategory.Z),
            new YokaiMedal("こえんら", 0xc24a, MedalCategory.Z),
            new YokaiMedal("化け草履", 0xc26a, MedalCategory.Z),
            new YokaiMedal("のっぺらぼう", 0xc27a, MedalCategory.Z),
            new YokaiMedal("一旦ゴメン", 0xc28a, MedalCategory.Z),
            new YokaiMedal("U.S.O", 0xc29a, MedalCategory.Z),
            new YokaiMedal("メゾンドワスレ", 0xc2ba, MedalCategory.Z),
            new YokaiMedal("えんらえんら", 0xc2da, MedalCategory.Z),
            new YokaiMedal("おでんじん", 0xc2ea, MedalCategory.Z),
            new YokaiMedal("あやまり倒し", 0xc2fa, MedalCategory.Z),
            new YokaiMedal("うんがい三面鏡", 0xc31a, MedalCategory.Z),
            new YokaiMedal("ぬえ", 0xc32a, MedalCategory.Z),
            new YokaiMedal("ドキ土器", 0xc34a, MedalCategory.Z),
            new YokaiMedal("うらや飯", 0xc36a, MedalCategory.Z),
            new YokaiMedal("迷い車", 0xc37a, MedalCategory.Z),
            new YokaiMedal("雷蔵", 0xc38a, MedalCategory.Z),
            new YokaiMedal("モノマネキン", 0xc39a, MedalCategory.Z),
            new YokaiMedal("あせっか鬼", 0xc3ba, MedalCategory.Z),
            new YokaiMedal("だっせんしゃ", 0xc3da, MedalCategory.Z),
            new YokaiMedal("プライ丼", 0xc3ea, MedalCategory.Z),
            new YokaiMedal("ヒライ神", 0xc3fa, MedalCategory.Z),
            new YokaiMedal("ガマンモス", 0xc41a, MedalCategory.Z),
            new YokaiMedal("百々目鬼", 0xc42a, MedalCategory.Z),
            new YokaiMedal("大ガマ", 0xc43a, MedalCategory.Z),
            new YokaiMedal("一つ目小僧", 0xc46a, MedalCategory.Z),
            new YokaiMedal("びきゃく", 0xc47a, MedalCategory.Z),
            new YokaiMedal("つらがわり", 0xc48a, MedalCategory.Z),
            new YokaiMedal("雨女", 0xc49a, MedalCategory.Z),
            new YokaiMedal("ばくそく", 0xc4ba, MedalCategory.Z),
            new YokaiMedal("おバく様", 0xc4da, MedalCategory.Z),
            new YokaiMedal("河童", 0xc4ea, MedalCategory.Z),
            new YokaiMedal("マスターニャーダ", 0xc4fa, MedalCategory.Z),
            new YokaiMedal("きらめき鬼", 0xc51a, MedalCategory.Z),
            new YokaiMedal("水虎", 0xc52a, MedalCategory.Z),
            new YokaiMedal("大やもり", 0xc54a, MedalCategory.Z),
            new YokaiMedal("いのちとり", 0xc56a, MedalCategory.Z),
            new YokaiMedal("風魔猿", 0xc58a, MedalCategory.Z),
            new YokaiMedal("こまじろう ゲラゲラポンモンゲー", 0xc5da, MedalCategory.Z),
            new YokaiMedal("コマさん ゲラゲラゲラポーずら", 0xc5ea, MedalCategory.Z),
            new YokaiMedal("キズナメコ", 0xc61a, MedalCategory.Z),
            new YokaiMedal("から傘お化け", 0xc62a, MedalCategory.Z),
            new YokaiMedal("砂夫", 0xc63a, MedalCategory.Z),
            new YokaiMedal("くだん", 0xc64a, MedalCategory.Z),
            new YokaiMedal("ざしきわらし", 0xc67a, MedalCategory.Z),
            new YokaiMedal("晴れ男", 0xc69a, MedalCategory.Z),
            new YokaiMedal("ワカメ☆スター", 0xc6ba, MedalCategory.Z),
            new YokaiMedal("キズナース", 0xc6da, MedalCategory.Z),
            new YokaiMedal("大山砂夫", 0xc6ea, MedalCategory.Z),
            new YokaiMedal("から傘魔人", 0xc6fa, MedalCategory.Z),
            new YokaiMedal("ざしきわら神", 0xc71a, MedalCategory.Z),
            new YokaiMedal("お金ナイダー", 0xc72a, MedalCategory.Z),
            new YokaiMedal("大くだん", 0xc73a, MedalCategory.Z),
            new YokaiMedal("麒麟", 0xc74a, MedalCategory.Z),
            new YokaiMedal("TETSUYA", 0xc76a, MedalCategory.Z),
            new YokaiMedal("かりパックン", 0xc78a, MedalCategory.Z),
            new YokaiMedal("草くいおとこ", 0xc79a, MedalCategory.Z),
            new YokaiMedal("まてんし", 0xc7ba, MedalCategory.Z),
            new YokaiMedal("ひとまか仙人", 0xc7da, MedalCategory.Z),
            new YokaiMedal("りもこんかくし", 0xc7ea, MedalCategory.Z),
            new YokaiMedal("ミツマタノヅチ", 0xc7fa, MedalCategory.Z),
            new YokaiMedal("リー夫人", 0xc81a, MedalCategory.Z),
            new YokaiMedal("ガブニャン", 0xc82a, MedalCategory.Z),
            new YokaiMedal("KANTETSU", 0xc83a, MedalCategory.Z),
            new YokaiMedal("肉くい男", 0xc84a, MedalCategory.Z),
            new YokaiMedal("泥ボックン", 0xc86a, MedalCategory.Z),
            new YokaiMedal("どんどろ", 0xc87a, MedalCategory.Z),
            new YokaiMedal("けうけげん", 0xc89a, MedalCategory.Z),
            new YokaiMedal("おともらし", 0xc8ba, MedalCategory.Z),
            new YokaiMedal("認MEN", 0xc8da, MedalCategory.Z),
            new YokaiMedal("じがじぃさん", 0xc8ea, MedalCategory.Z),
            new YokaiMedal("花子さん", 0xc8fa, MedalCategory.Z),
            new YokaiMedal("のらりくらり", 0xc91a, MedalCategory.Z),
            new YokaiMedal("ぶんぶん鳥", 0xc92a, MedalCategory.Z),
            new YokaiMedal("のぼせトンマン", 0xc93a, MedalCategory.Z),
            new YokaiMedal("爆音ならし", 0xc94a, MedalCategory.Z),
            new YokaiMedal("ふさふさん", 0xc96a, MedalCategory.Z),
            new YokaiMedal("呪野花子", 0xc97a, MedalCategory.Z),
            new YokaiMedal("土蜘蛛", 0xc98a, MedalCategory.Z),
            new YokaiMedal("ケマモン", 0xc9ba, MedalCategory.Z),
            new YokaiMedal("ねちがえる", 0xc9da, MedalCategory.Z),
            new YokaiMedal("からみぞん", 0xc9ea, MedalCategory.Z),
            new YokaiMedal("おもいだスッポン", 0xc9fa, MedalCategory.Z),
            new YokaiMedal("つられたろう丸", 0xcb1a, MedalCategory.Z),
            new YokaiMedal("ムカムカデ", 0xcb2a, MedalCategory.Z),
            new YokaiMedal("にんぎょ", 0xcb3a, MedalCategory.Z),
            new YokaiMedal("ろくろ首", 0xcb4a, MedalCategory.Z),
            new YokaiMedal("ホリュウ", 0xcb6a, MedalCategory.Z),
            new YokaiMedal("激ドラゴン", 0xcb7a, MedalCategory.Z),
            new YokaiMedal("おもいだ神", 0xcb8a, MedalCategory.Z),
            new YokaiMedal("こんがらギャル", 0xcb9a, MedalCategory.Z),
            new YokaiMedal("八百比丘尼", 0xcbda, MedalCategory.Z),
            new YokaiMedal("ネタバレリーナ", 0xcbea, MedalCategory.Z),
            new YokaiMedal("うんちく魔", 0xcbfa, MedalCategory.Z),
            new YokaiMedal("やまタン", 0xcd1a, MedalCategory.Z),
            new YokaiMedal("ジバニャン コマニャチ", 0xd9ca, MedalCategory.Z),
            new YokaiMedal("ジバニャン ニャイーン", 0xd9ea, MedalCategory.Z),
            new YokaiMedal("ジバニャン ニョエー", 0xd9fa, MedalCategory.Z),
            new YokaiMedal("フユニャン", 0xdb1a, MedalCategory.Z),

            new YokaiMedal("コールのみ", 0xdb8a, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0xdb9a, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0xdbca, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0xdbea, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0xdbfa, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0xdc1a, MedalCategory.Z),
            new YokaiMedal("コールのみ", 0xdc2a, MedalCategory.Z),

            new YokaiMedal("ロボニャン オイ何とか", 0xe51a, MedalCategory.Z),
            new YokaiMedal("ドンヨリーヌ モージョーン", 0xe52a, MedalCategory.Z),
            new YokaiMedal("ツチノコ キュピーン", 0xe53a, MedalCategory.Z),
            new YokaiMedal("ホノボーノ ボーノー", 0xe54a, MedalCategory.Z),
            new YokaiMedal("キュウビ", 0xe56a, MedalCategory.Z),
            new YokaiMedal("メラメライオン メラメラー", 0xe57a, MedalCategory.Z),
            new YokaiMedal("オロチ", 0xe58a, MedalCategory.Z),
            new YokaiMedal("ひもじぃ ひーもー", 0xe59a, MedalCategory.Z),
            new YokaiMedal("じんめん犬 チクショー", 0xe5ba, MedalCategory.Z),
            new YokaiMedal("バクロ婆 ババーン", 0xe5ca, MedalCategory.Z),
            new YokaiMedal("コマさん もんげー", 0xe5da, MedalCategory.Z),
            new YokaiMedal("セバスチャン", 0xe5fa, MedalCategory.Z),
            new YokaiMedal("ブドウニャン", 0xf51a, MedalCategory.Z),
            new YokaiMedal("ろくろ首怪", 0xf52a, MedalCategory.Z),
            new YokaiMedal("ミカンニャン", 0xf53a, MedalCategory.Z),
            new YokaiMedal("にんぎょ怪", 0xf54a, MedalCategory.Z),
            new YokaiMedal("くだん怪", 0xf56a, MedalCategory.Z),
            new YokaiMedal("から傘お化け怪", 0xf57a, MedalCategory.Z),
            new YokaiMedal("けうけげん怪", 0xf58a, MedalCategory.Z),
            new YokaiMedal("ロボG", 0xf59a, MedalCategory.Z),
            new YokaiMedal("河童怪", 0xf5ba, MedalCategory.Z),
            new YokaiMedal("ざしきわらし怪", 0xf5ca, MedalCategory.Z),
            new YokaiMedal("えんらえんら怪", 0xf5da, MedalCategory.Z),
            new YokaiMedal("ロボコマ おどろきずらモンゲー", 0xf5ea, MedalCategory.Z)
        );
    }

}
